//! Raw FFI bindings to whisper.cpp
//!
//! This module contains the raw FFI bindings to the whisper.cpp library.
//! These are automatically generated by bindgen during the build process.
//!
//! Users should not use these directly, but instead use the safe wrapper
//! types provided by this crate.

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]

// Include the generated bindings
include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
